#include "desktopintegration.h"
#include "conversion.h"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QStandardPaths>
#include <QUuid>

namespace
{
const QByteArray marker = "Generated by Athanor";
struct Group
{
    QString name, inputType, mime;
    QStringList extensions, targets, labels;
};
QList<Group> groups()
{
    return {{"Images", "image", "image/*;", Conversion::imageExtensions(),
             {"avif", "webp", "heic", "heif", "jpg", "png", "ico", "images-pdf"},
             {"Convert to AVIF", "Convert to WebP", "Convert to HEIC", "Convert to HEIF", "Convert to JPG",
              "Convert to PNG", "Convert to ICO", "Create PDF"}},
            {"Video", "movie", "video/*;image/gif;", Conversion::videoExtensions(),
             {"webm", "mkv", "av1", "mp4", "gif", "opus", "mp3", "wav"},
             {"Convert to WebM", "Convert to MKV", "Convert to .av1 (video only)", "Convert to MP4",
              "Convert to GIF", "Extract Opus audio", "Extract MP3 audio", "Extract WAV audio"}},
            {"Audio", "audio", "audio/*;", Conversion::audioExtensions(), {"opus", "mp3", "wav"},
             {"Convert to Opus", "Convert to MP3", "Convert to WAV"}},
            {"PDF", "pdf", "application/pdf;", {"pdf"}, {"pdf", "pdf-jpg"},
             {"Compress PDF", "Export JPG pages"}}};
}
bool noLinks(const QString &path)
{
    QFileInfo info(path);
    while (true)
    {
        if (info.isSymLink())
            return false;
        auto parent = info.absolutePath();
        if (parent == info.absoluteFilePath())
            return true;
        info.setFile(parent);
    }
}
bool ownedWrite(const QString &path, const QByteArray &bytes, bool enabled, bool executable = false)
{
    if (!noLinks(path))
        return false;
    QFile existing(path);
    if (existing.exists())
    {
        if (!existing.open(QIODevice::ReadOnly) || !existing.readAll().contains(marker))
            return false;
        existing.close();
        if (!enabled)
            return existing.remove();
    }
    if (!enabled)
        return true;
    if (!QDir().mkpath(QFileInfo(path).absolutePath()))
        return false;
    QSaveFile output(path);
    if (!output.open(QIODevice::WriteOnly) || output.write(bytes) != bytes.size() || !output.commit())
        return false;
    return !executable || QFile::setPermissions(path, QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner);
}
QString shellQuote(QString value)
{
    value.replace("'", "'\\''");
    return "'" + value + "'";
}
QString desktopQuote(QString value)
{
    value.replace('\\', "\\\\\\\\");
    value.replace('"', "\\\"");
    value.replace('`', "\\`");
    value.replace('$', "\\$");
    value.replace('%', "%%");
    return '"' + value + '"';
}
QString script(const QString &executable, const Group &group, const QString &target)
{
    QStringList patterns;
    for (const auto &ext : group.extensions)
        patterns << "*." + ext;
    return "#!/bin/bash\n# Generated by Athanor\n" 
           "if [ \"$#\" -eq 0 ]; then\n"
           "  files=${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS:-${NEMO_SCRIPT_SELECTED_FILE_PATHS:-}}\n"
           "  while IFS= read -r file; do [ -z \"$file\" ] || set -- \"$@\" \"$file\"; done <<< \"$files\"\n"
           "fi\nselected=()\nfor file in \"$@\"; do\n"
           "  lower=$(printf '%s' \"$file\" | tr '[:upper:]' '[:lower:]')\n"
           "  case \"$lower\" in " + patterns.join('|') + ") selected+=(\"$file\");; esac\n"
           "done\n[ \"${#selected[@]}\" -gt 0 ] || exit 0\nexec " + shellQuote(executable) +
           " --quick --target " + shellQuote(target) + " -- \"${selected[@]}\"\n";
}
QString workflow(const QString &command, const QString &type)
{
    const auto uuid = QUuid::createUuid().toString(QUuid::WithoutBraces);
    // Finder Quick Actions use the system Run Shell Script action; inputMethod=1
    // passes each selected path as an argument, preserving spaces and Unicode.
    return QString::fromUtf8(R"XML(<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict><!-- Generated by Athanor -->
<key>AMDocumentVersion</key><string>2</string>
<key>actions</key><array><dict><key>action</key><dict>
<key>AMAccepts</key><dict><key>Container</key><string>List</string><key>Optional</key><true/><key>Types</key><array><string>com.apple.cocoa.path</string></array></dict>
<key>AMProvides</key><dict><key>Container</key><string>List</string><key>Types</key><array><string>com.apple.cocoa.string</string></array></dict>
<key>ActionBundlePath</key><string>/System/Library/Automator/Run Shell Script.action</string>
<key>ActionName</key><string>Run Shell Script</string>
<key>ActionParameters</key><dict><key>COMMAND_STRING</key><string>%1</string><key>inputMethod</key><integer>1</integer><key>shell</key><string>/bin/bash</string><key>source</key><string></string></dict>
<key>BundleIdentifier</key><string>com.apple.RunShellScript</string>
<key>Class Name</key><string>RunShellScriptAction</string>
<key>UUID</key><string>%2</string><key>InputUUID</key><string>%2-input</string><key>OutputUUID</key><string>%2-output</string>
</dict></dict></array><key>connectors</key><dict/>
<key>workflowMetaData</key><dict>
<key>serviceApplicationBundleID</key><string>com.apple.finder</string>
<key>serviceApplicationPath</key><string>/System/Library/CoreServices/Finder.app</string>
<key>serviceInputTypeIdentifier</key><string>com.apple.Automator.fileSystemObject.%3</string>
<key>serviceOutputTypeIdentifier</key><string>com.apple.Automator.nothing</string>
<key>serviceProcessesInput</key><integer>0</integer>
<key>workflowTypeIdentifier</key><string>com.apple.Automator.servicesMenu</string>
</dict></dict></plist>)XML")
        .arg(command.toHtmlEscaped(), uuid, type);
}
}
bool DesktopIntegration::configure(bool enabled, const QString &executable, QString *error)
{
    bool ok = true;
#ifdef Q_OS_MACOS
    const auto root = qEnvironmentVariable("ATHANOR_INTEGRATION_DIR", QDir::homePath() + "/Library/Services");
    for (const auto &group : groups())
        for (int i = 0; i < group.targets.size(); i++)
        {
            const auto bundle = root + "/Athanor - " + group.name + " - " + group.labels[i] + ".workflow";
            const auto path = bundle + "/Contents/document.wflow";
            ok = ownedWrite(path, workflow(script(executable, group, group.targets[i]), group.inputType).toUtf8(), enabled) && ok;
            if (!enabled && noLinks(bundle))
            {
                QDir().rmdir(bundle + "/Contents");
                QDir().rmdir(bundle);
            }
        }
#elif defined(Q_OS_LINUX)
    const auto root = qEnvironmentVariable("ATHANOR_INTEGRATION_DIR", QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation));
    for (const auto &group : groups())
        for (int i = 0; i < group.targets.size(); i++)
        {
            const auto relative = "/Athanor/" + group.name + " - " + group.labels[i];
            const auto command = script(executable, group, group.targets[i]).toUtf8();
            for (const auto &manager : {QString("nautilus"), QString("nemo")})
                ok = ownedWrite(root + '/' + manager + "/scripts" + relative, command, enabled, true) && ok;
            const auto launcher = root + "/athanor/actions/" + group.name + '-' + group.targets[i];
            ok = ownedWrite(launcher, command, enabled, true) && ok;
            const auto service = "[Desktop Entry]\n# Generated by Athanor\nType=Service\nMimeType=" + group.mime +
                                 "\nActions=convert;\nX-KDE-Submenu=Convert using Athanor\n[Desktop Action convert]\nName=" +
                                 group.labels[i] + "\nExec=" + desktopQuote(launcher) + " %F\n";
            ok = ownedWrite(root + "/kio/servicemenus/athanor-" + group.name + '-' + group.targets[i] + ".desktop", service.toUtf8(), enabled, true) && ok;
        }
#else
    Q_UNUSED(enabled);
    Q_UNUSED(executable);
#endif
    if (!ok && error)
        *error = "Could not save file manager actions. Check permissions and existing Athanor action files.";
    return ok;
}
