# System prefixes, Homebrew, vcpkg and source-built SDKs all use this interface.
add_library(AthanorCodecs INTERFACE)
find_path(MUPDF_INCLUDE_DIR mupdf/fitz.h HINTS "${ATHANOR_MUPDF_ROOT}/include" REQUIRED)
find_library(MUPDF_LIBRARY NAMES mupdf libmupdf HINTS "${ATHANOR_MUPDF_ROOT}/lib" REQUIRED)
find_library(MUPDF_THIRD_LIBRARY NAMES mupdf-third libthirdparty HINTS "${ATHANOR_MUPDF_ROOT}/lib")
target_include_directories(AthanorCodecs INTERFACE "${MUPDF_INCLUDE_DIR}")
target_link_libraries(AthanorCodecs INTERFACE "${MUPDF_LIBRARY}")
if(MUPDF_THIRD_LIBRARY)
 target_link_libraries(AthanorCodecs INTERFACE "${MUPDF_THIRD_LIBRARY}")
endif()
if(UNIX)
 target_link_libraries(AthanorCodecs INTERFACE m)
endif()
find_package(libavif CONFIG QUIET)
if(TARGET avif)
 target_link_libraries(AthanorCodecs INTERFACE avif)
else()
 find_path(AVIF_INCLUDE_DIR avif/avif.h REQUIRED)
 find_library(AVIF_LIBRARY avif REQUIRED)
 target_include_directories(AthanorCodecs INTERFACE "${AVIF_INCLUDE_DIR}")
 target_link_libraries(AthanorCodecs INTERFACE "${AVIF_LIBRARY}")
endif()
find_package(libheif CONFIG QUIET)
if(TARGET heif)
 target_link_libraries(AthanorCodecs INTERFACE heif)
else()
 find_path(HEIF_INCLUDE_DIR libheif/heif.h REQUIRED)
 find_library(HEIF_LIBRARY heif REQUIRED)
 target_include_directories(AthanorCodecs INTERFACE "${HEIF_INCLUDE_DIR}")
 target_link_libraries(AthanorCodecs INTERFACE "${HEIF_LIBRARY}")
endif()
find_package(WebP CONFIG QUIET)
if(TARGET WebP::webp)
 target_link_libraries(AthanorCodecs INTERFACE WebP::webp WebP::webpdemux)
 if(TARGET WebP::webpmux)
  target_link_libraries(AthanorCodecs INTERFACE WebP::webpmux)
 else()
  target_link_libraries(AthanorCodecs INTERFACE WebP::libwebpmux)
 endif()
else()
 find_path(WEBP_INCLUDE_DIR webp/encode.h REQUIRED)
 foreach(lib webp webpmux webpdemux)
  find_library(${lib}_LIBRARY ${lib} REQUIRED)
  target_link_libraries(AthanorCodecs INTERFACE "${${lib}_LIBRARY}")
 endforeach()
 target_include_directories(AthanorCodecs INTERFACE "${WEBP_INCLUDE_DIR}")
endif()
